site_name: VS Code Prototype
site_description: Test environment for validating VS Code configurations and Python tooling integration
site_url: https://rawtechllc.github.io/vscode-prototype/
repo_url: https://github.com/RAWTechLLC/vscode-prototype
repo_name: RAWTechLLC/vscode-prototype
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - First Steps: getting-started/first-steps.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Development Workflow: user-guide/development-workflow.md
    - Environment Setup: user-guide/environment-setup.md
    - VS Code Integration: user-guide/vscode-integration.md
    - Extensions: user-guide/extensions.md
  - API Reference:
    - Data Processor: api/data_processor.md
  - Best Practices:
    - Code Style: best-practices/code-style.md
    - Documentation: best-practices/documentation.md
    - Git Workflow: best-practices/git-workflow.md
    - Testing: best-practices/testing.md
  - Contributing:
    - Guidelines: contributing/guidelines.md
    - Development Setup: contributing/development-setup.md
    - GitHub Pages Setup: contributing/github-pages-setup.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RAWTechLLC/vscode-prototype
      name: VS Code Prototype on GitHub

use_directory_urls: true
